name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t docker-image:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker tag <your-image-name>:latest ghcr.io/Jlaborne/holbertonschool-higher_level_programming:latest
          docker push ghcr.io/Jlaborne/holbertonschool-higher_level_programming:latest
